<a href="https://colab.research.google.com/github/bigdatakang0000/START/blob/main/%EC%8B%A4%EC%8A%B5230103.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

빅데이터마케팅 분석 전문가#2
강경숙 
2023.01.12

In [16]:
a = 123
b =  abc
print(type("a"), type("b"))
print("a", "b")

NameError: ignored

In [11]:
Tuple = ("a","b","c","d")

In [14]:
score = 60
if score > 40 :
    print("vip")
else :
    print("member")

vip


In [ ]:
for i in 

In [17]:
customer_count = 0
sum1 = 0

print( "customer_count_sum")

while(sum1<20) :
    customer_count = customer_count +1
    sum1= sum1 +customer_count
    print(customer_count,sum1)

customer_count_sum
1 1
2 3
3 6
4 10
5 15
6 21


In [ ]:
#Numpy


In [18]:
from matplotlib import pyplot as plt
from pandas import DataFrame
import numpy as np
from pandas import *



In [19]:
data = [1,2,3,4,5,6]
arr1= np.array(data)
arr1

array([1, 2, 3, 4, 5, 6])

In [24]:
arr1.dtype

dtype('int64')

In [23]:
arr1 = np.arange(start = 1, stop = 20, step = 2)
print(arr1)

[ 1  3  5  7  9 11 13 15 17 19]


In [25]:
arr1=np.array([10,12,14,16,18])
arr2=np.array([3,4,5,6,7])

print("더하기")
print(arr1+arr2)
print("----빼기----")
print(arr1-arr2)
print("----곱하기----")
print(arr1*arr2)
print("----나누기----")
print(arr1/arr2)

더하기
[13 16 19 22 25]
----빼기----
[ 7  8  9 10 11]
----곱하기----
[ 30  48  70  96 126]
----나누기----
[3.33333333 3.         2.8        2.66666667 2.57142857]
